OS_name: "centos/8"
OS_version: ">= 0"
OS_url: "https://vagrantcloud.com/centos/8"
server:
  cpus: 1
  memory: 1024
node:
  cpus: 1
  memory: 1024
ip:
  server: "192.168.42.110"
  node: "192.168.42.111"
net:
  network_type: "private_network"
