# -*- mode: ruby -*-
# vi: set ft=ruby :

# Specify Vagrant API version
VAGRANTFILE_API_VERSION = "2"

# Require YAML module
require 'yaml'

# Read YAML config file
c = YAML.load_file(File.join(File.dirname(__FILE__), "confs/config.yaml"))

# Specify OS details
OS_NAME =  c.fetch('OS_name')
OS_VERSION = c.fetch('OS_version')
OS_URL = c.fetch('OS_url')

# Disable Firewall
$DISABLE_FIREWALL = <<-SHELL
    echo "Disabling Firewall..."
    sudo systemctl disable firewalld --now
    SHELL

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    
    config.vagrant.plugins = ['vagrant-vbguest']
    config.vbguest.auto_update = true
    config.vbguest.installer_options = { allow_kernel_upgrade: true }
    config.vm.box = OS_NAME
    config.vm.box_version = OS_VERSION
    config.vm.box_url = OS_URL
    config.vm.box_check_update = false
    config.vm.provision "shell", inline: $DISABLE_FIREWALL
    
    config.vm.define "ishaimouS" do |server|
        s = c.fetch('server')
        server_ip = s.fetch('ip')
        server.vm.provider "virtualbox" do |vb|
            vb.name = "ishaimouS"
            vb.memory = s.fetch('memory')
            vb.cpus = s.fetch('cpus')
        end
        server.vm.synced_folder "./confs", "/vagrant_shared"
        server.vm.network c.fetch('net').fetch('network_type'), ip: server_ip
        server.vm.hostname = "ishaimouS"
        server.vm.provision "shell", inline: "echo installing k3s server on ishaimouS Server"
        server.vm.provision "shell", path: "./scripts/ishaimouS.sh", args: [server_ip]
        server.vm.provision "shell", path: "./scripts/deploy.sh"
    end
    
end