# -*- mode: ruby -*-
# vi: set ft=ruby :

# Specify Vagrant API version
VAGRANTFILE_API_VERSION = "2"

# Require YAML module
require 'yaml'

# Read YAML config file
c = YAML.load_file(File.join(File.dirname(__FILE__), "confs/config.yaml"))

# Specify OS details
OS_NAME =  c.fetch('OS_name')
OS_VERSION = c.fetch('OS_version')
OS_URL = c.fetch('OS_url')

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    server_ip = c.fetch('ip').fetch('server')

    config.vagrant.plugins = ['vagrant-vbguest']
    config.vbguest.auto_update = true
    config.vbguest.installer_options = { allow_kernel_upgrade: true }
    config.vm.box = OS_NAME
    config.vm.box_version = OS_VERSION
    config.vm.box_url = OS_URL
    config.vm.box_check_update = false
    
    config.vm.define "ishaimouS" do |server|
        s = c.fetch('server')
        server.vm.provider "virtualbox" do |vb|
            vb.customize ["modifyvm", :id, "--natdnsproxy1", "on", "--natdnshostresolver1", "on"]
            vb.name = "ishaimouS"
            vb.gui = false
            vb.memory = s.fetch('memory')
            vb.cpus = s.fetch('cpus')
        end
        server.vm.synced_folder "./confs", "/vagrant_shared"
        server.vm.network c.fetch('net').fetch('network_type'), ip: server_ip
        server.vm.hostname = "ishaimouS"
        server.vm.provision :shell, inline: "echo installing k3s server on ishaimouS Server Node"
        server.vm.provision "shell" do |s|
            s.path = "./scripts/ishaimouS.sh"
            s.args = [server_ip]
        end
    end

    config.vm.define "ishaimouSW" do |node|
        n = c.fetch('node')
        node_ip =  c.fetch('ip').fetch('node')
        node.vm.provider "virtualbox" do |vb|
            vb.customize ["modifyvm", :id, "--natdnsproxy1", "on", "--natdnshostresolver1", "on"]
            vb.name = "ishaimouSW"
            vb.gui = false
            vb.memory = n.fetch('memory')
            vb.cpus = n.fetch('cpus')
        end
        node.vm.synced_folder "./confs", "/vagrant_shared"
        node.vm.network c.fetch('net').fetch('network_type'), ip: node_ip
        node.vm.hostname = "ishaimouSW"
        node.vm.provision :shell, inline: "echo installing k3s agent on ishaimouSW Worker Node"
        node.vm.provision "shell" do |s|
            s.path = "./scripts/ishaimouSW.sh"
            s.args = [server_ip]
        end
    end
    
end